version: '3.8'

services:
  postgres:
    image: 'postgres:alpine'

    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=galopez
      - POSTGRES_USER=galopez
      - POSTGRES_PASSWORD=SaraRamos2020!
  server:
    build: ./
    image: samc621/sneakerbot
    ports:
      - '8080:8080'
      - '5900:5900'
    depends_on:
      - postgres
    environment:
      - NODE_ENV=docker
    env_file:
      - .env.docker

volumes:
  db-data:
